//
// Created by Kovacs család on 2019-02-06.
//

#ifndef INSTRUMENTS_TO_STRINGED_INSTRUMENTS_BASSGUITAR_H
#define INSTRUMENTS_TO_STRINGED_INSTRUMENTS_BASSGUITAR_H

class bassGuitar
{

};

#endif //INSTRUMENTS_TO_STRINGED_INSTRUMENTS_BASSGUITAR_H
