//
// Created by Kovacs család on 2019-02-06.
//

#ifndef INSTRUMENTS_TO_STRINGED_INSTRUMENTS_INSTRUMENT_H
#define INSTRUMENTS_TO_STRINGED_INSTRUMENTS_INSTRUMENT_H

class instrument
{

};

#endif //INSTRUMENTS_TO_STRINGED_INSTRUMENTS_INSTRUMENT_H
