//
// Created by Kovacs család on 2019-02-06.
//

#ifndef INSTRUMENTS_TO_STRINGED_INSTRUMENTS_STRIGEDINSTRUMENT_H
#define INSTRUMENTS_TO_STRINGED_INSTRUMENTS_STRIGEDINSTRUMENT_H

class strigedInstrument
{

};

#endif //INSTRUMENTS_TO_STRINGED_INSTRUMENTS_STRIGEDINSTRUMENT_H
