//
// Created by Kovacs család on 2019-02-06.
//

#ifndef INSTRUMENTS_TO_STRINGED_INSTRUMENTS_VIOLIN_H
#define INSTRUMENTS_TO_STRINGED_INSTRUMENTS_VIOLIN_H

class violin
{

};

#endif //INSTRUMENTS_TO_STRINGED_INSTRUMENTS_VIOLIN_H
